embedding_model:
  provider: "google"
  model_name: "models/text-embedding-004"

retriever:
  top_k: 4

llm:
  google:
    provider: "google"
    model_name: "gemini-2.0-flash"
    temperature: 0
    max_output_tokens: 2048